---
- name: Converge
  hosts: all
  become: true # Ejecutar tareas como root
  gather_facts: true

  vars:
    # Variables de base de datos para el rol geerlingguy.mysql
    mysql_root_password: "Micontrasenia123-"

    mysql_root_login_password: "{{ mysql_root_password }}"
    mysql_databases:
      - name: "{{ wordpress_db_name }}"
    mysql_users:
      - name: "{{ wordpress_db_user }}"
        host: "127.0.0.1" # O 'localhost'
        password: "{{ wordpress_db_password }}"
        priv: "{{ wordpress_db_name }}.*:ALL"
    mysql_daemon: "{{ 'mariadb' if ansible_os_family == 'RedHat' else 'mysql' }}"

  pre_tasks:
    - name: Ensure Python and sudo are installed (Docker containers)
      ansible.builtin.raw: |
        apt update && apt install -y python3 python3-pip sudo || \
        dnf install -y python3 python3-pip sudo || \
        yum install -y python3 python3-pip sudo
      changed_when: false
      failed_when: false

  roles:
    - ../../..        # Nuestro rol personalizado para el servidor web
