---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: molecule-ubuntu
    image: ubuntu:20.04
  - name: molecule-rocky
    image: rockylinux:9

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
  config_options:
    defaults:
      interpreter_python: auto
  inventory:
    group_vars:
      all:
        wordpress_install_dir: /var/www/wordpress
        wordpress_db_name: wordpress_db
        wordpress_db_user: wordpress_user
        wordpress_db_password: Micontrasenia123-
        wordpress_site_url: http://127.0.0.1
        wordpress_version: "6.5"
        wordpress_download_url: "https://wordpress.org/wordpress-{{ wordpress_version }}.zip"

verifier:
  name: ansible

