---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance-ubuntu
    box: ubuntu/focal64
    networks:
      - forwarded_port:
          guest: 80
          host: 8080
    memory: 1024
  - name: instance-rocky
    box: rockylinux/9
    interfaces:
      - auto_config: true
        network_name: private_network
        ip: 192.168.56.11
    networks:
      - forwarded_port:
          guest: 80
          host: 8090
    memory: 1024
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  config_options:
    defaults:
      interpreter_python: auto
  inventory:
    group_vars:
      all:
        wordpress_install_dir: /var/www/wordpress
        wordpress_db_name: wordpress_db
        wordpress_db_user: wordpress_user
        wordpress_db_password: Micontrasenia123-
        wordpress_site_url: http://127.0.0.1
        wordpress_version: "6.5"
        wordpress_download_url: "https://wordpress.org/wordpress-{{ wordpress_version }}.zip"
verifier:
  name: ansible
