# .github/workflows/molecule.yml
name: Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule
          ansible-galaxy collection install community.general
          ansible-galaxy install geerlingguy.mysql geerlingguy.php

      - name: Install Vagrant
        run: |
          wget https://releases.hashicorp.com/vagrant/2.4.1/vagrant_2.4.1-1_amd64.deb -O vagrant.deb
          sudo dpkg -i vagrant.deb || sudo apt-get install -f -y
      
      - name: Run Molecule tests
        working-directory: roles/webserver
        run: |
          molecule test
